name: "code-upload"
namespace: "argo-workflows"
ttl: "10:00"
code:
  path: "./"
steps:
  - name: "step"
    image: "rocm/pytorch:rocm7.2_ubuntu24.04_py3.12_pytorch_release_2.7.1"
    resources:
      cpus_per_node: "AUTO" # When requesting GPUs, setting CPU/Mem to AUTO will automatically request 1/8th of a node of CPU/Mem per GPU
      mem_per_node: "AUTO"
      ephemeral_storage_per_node: "AUTO"
      gpus_per_node: 8
      gpu_type: "amd.com/gpu"
    script: |
      echo NNODES=$NNODES
      echo NODE_RANK=$NODE_RANK
      echo MASTER_ADDR=$MASTER_ADDR
      echo MASTER_PORT=$MASTER_PORT
      torchrun --nproc_per_node=$GPUS_PER_NODE --nnodes=$NNODES --node_rank=$NODE_RANK --master_addr=$MASTER_ADDR --master_port=$MASTER_PORT job.py
