[SERVICE]
    Flush        1
    Grace        30
    # Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              ${SEEKR_CHAIN_LOGS}
    Tag               myapp
    Refresh_Interval  2
    Skip_Long_Lines   On
    Mem_Buf_Limit     64MB
    # Start at end so we don't re-upload old bytes on first boot:
    Read_from_Head    On
    DB                /seekr-chain/fb-tail.db
    DB.locking        true
    # storage.type    filesystem

[OUTPUT]
    Name              s3
    Match             myapp
    bucket            ${S3_BUCKET}
    # Upload chunks on size or timeout
    total_file_size   128M
    upload_timeout    ${FB_UPLOAD_TIMEOUT}
    store_dir         /seekr-chain/buffers
    # Unique object key per chunk
    s3_key_format     /${S3_STEP_DATA_PREFIX}/attempt=${RESTART_ATTEMPT}/logs/%Y%m%d-%H%M%S.log.gz
    # Compress logs
    compression       gzip
