FROM python:3.12-slim

# Install system deps
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    git \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# Install kubectl (latest stable)
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# Install argo
RUN curl -sLO "https://github.com/argoproj/argo-workflows/releases/download/v3.5.15/argo-linux-amd64.gz" \
    && gunzip "argo-linux-amd64.gz" \
    # && rm "argo-linux-amd64.gz" \
    && chmod +x "argo-linux-amd64" \
    && mv "./argo-linux-amd64" /usr/local/bin/argo

RUN pip install oci-cli
